forum/articles/urls.py
from django.urls import path

from . import views

# Articles
urlpatterns = [
    path("", views.view_article_list, name="list"),
    path("<int:pk>/", views.view_article_detail, name="detail"),
    path("create/", views.view_article_create, name="create"),
    path("<int:pk>/edit/", views.view_article_edit, name="edit"),
    path("<int:pk>/delete/", views.view_article_delete, name="delete"),
]

forum/forum/urls.py
from django.urls import path

from . import views
from .views.feed import LatestEntriesFeed

urlpatterns = [
    path("", views.view_home, name="home"),
    path("questions/", views.view_questions, name="list"),
    path("questions/tag/<str:tag_word>/", views.view_tag_questions_list, name="tag"),
    path("questions/<int:pk>/", views.view_single_question, name="thread"),
    path("questions/ask", views.view_askquestion, name="ask"),
    path("question/<int:pk>/edit", views.view_editquestion, name="question_edit"),
    path(
        "questions/answer/<int:answer_pk>/edit",
        views.view_editanswer,
        name="answer_edit",
    ),
    path("question/<int:pk>/delete", views.view_delete_question, name="question_delete"),
    path(
        "question/<int:question_pk>/delete/<int:answer_pk>",
        views.view_delete_answer,
        name="answer_delete",
    ),
]
# Partials
urlpatterns += [
    path(
        "questions/<int:question_pk>/tags",
        views.view_partial_question_tags,
        name="question_tags",
    ),
    path(
        "<str:post_type>/<int:post_pk>/comments",
        views.view_partial_post_comments,
        name="post_comments",
    ),
    path(
        "questions/<int:question_pk>/invites",
        views.view_partial_invites,
        name="questions_invites",
    ),
    path("users/navbar", views.view_partial_user_navbar, name="user_navbar"),
    path("similar-questions/", views.view_similar_questions, name="similar"),
    path("tags/<int:pk>/popover", views.view_partial_tag_popover, name="tag_popover"),
]
# Actions
urlpatterns += [
    path("question/<int:pk>/follow/", views.view_follow_question, name="follow"),
    path("question/<int:pk>/unfollow/", views.view_unfollow_question, name="unfollow"),
    path(
        "question/<int:question_pk>/bookmark",
        views.view_bookmark_question,
        name="bookmark",
    ),
    path(
        "question/<int:question_pk>/unbookmark",
        views.view_unbookmark_question,
        name="unbookmark",
    ),
    path("usertags/<str:tag_word>/watch", views.view_user_follow_tag, name="watch_tag"),
    path(
        "usertags/<str:tag_word>/unwatch",
        views.view_user_unfollow_tag,
        name="unwatch_tag",
    ),
    path(
        "question/<int:question_pk>/invite_to_question",
        views.view_invite_to_question,
        name="invite",
    ),
    path(
        "question/<int:question_pk>/download_markdown",
        views.view_download_thread,
        name="markdown",
    ),
    path(
        "question/<int:pk>/upvote_comment/<str:parent_model_name>/<int:comment_pk>",
        views.view_upvote_comment,
        name="comment_upvote",
    ),
    path(
        "question/<int:pk>/delete_comment/<str:model>/<int:comment_id>",
        views.view_deletecomment,
        name="comment_delete",
    ),
]
# Automatic actions
urlpatterns += [
    path(
        "question/<int:pk>/upvote/<str:model_name>/<int:model_pk>",
        views.view_upvote,
        name="upvote",
    ),
    path(
        "question/<int:pk>/downvote/<str:model_name>/<int:model_pk>",
        views.view_downvote,
        name="downvote",
    ),
    path(
        "mark_as_seen/<int:vote_activity_pk>/",
        views.view_mark_as_seen,
        name="mark_seen",
    ),
    path("mark_all_as_seen/", views.view_all_mark_as_seen, name="mark_all_seen"),
    path(
        "question/<int:question_pk>/accept/<int:answer_pk>",
        views.view_acceptanswer,
        name="answer_accept",
    ),
]

urlpatterns += [
    path("users-autocomplete/", views.view_users_autocomplete, name="users_autocomplete"),
    path("users-get/", views.view_get_users_data, name="users-get"),
    path("image-upload/", views.view_image_upload, name="image_upload"),
]
# Slack
urlpatterns += [
    path("integrations/slack_post/", views.view_slack_post, name="slack-post"),
    path(
        "integrations/tags_autocomplete/",
        views.view_tags_autocomplete_for_slack,
        name="slack-tags-autocomplete",
    ),
    path("integrations/slack_search/", views.search_from_slack, name="slack-search"),
]

# RSS
urlpatterns += [
    path("rss/feed/", LatestEntriesFeed()),
    path("editing-help/", views.view_markdown_help),
]

# One time code
from wiwik_lib.templatetags.wiwik_template_tags import check_latex_config  # noqa: E402
from forum.integrations.slack_api import configure_slack_client  # noqa: E402

check_latex_config()
configure_slack_client()

forum/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include(("forum.urls", "forum"), namespace="forum")),
    path("articles/", include(("articles.urls", "articles"), namespace="articles")),
    path("BB-aDmin/", admin.site.urls),  # intentionally non-standard to prevent casual hacking tries.
    path("scheduler/", include("scheduler.urls")),
    path("accounts/", include("allauth.urls")),
    path("users/", include(("userauth.urls", "userauth"), namespace="userauth")),
    path("badges/", include(("badges.urls", "badges"), namespace="badges")),
    path("tags/", include(("tags.urls", "tags"), namespace="tags")),
    path("general/", include(("wiwik_lib.urls", "wiwik_lib"), namespace="general")),
    path("spaces/", include(("spaces.urls", "spaces"), namespace="spaces")),
    path(
        "similarity/",
        include(("similarity.urls", "similarity"), namespace="similarity"),
    ),
]

if settings.DEBUG_TOOLS:
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

forum/spaces/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("user-spaces", views.view_side_menu_user_spaces, name="user-spaces"),
    path("<str:space_id>/info", views.view_space_info, name="detail"),
    path("<int:space_id>/edit", views.view_space_edit, name="edit"),
    path("<str:space_id>/leave", views.view_space_leave, name="leave"),
    path("<str:space_id>/join", views.view_space_join, name="join"),
    path("<str:space_id>/questions", views.view_space_questions, name="questions"),
    path(
        "latest-questions",
        views.view_user_spaces_latest_questions,
        name="user-spaces-questions",
    ),
    path("property/<str:property_name>", views.view_property_info, name="property-info"),
]

forum/spaces/views/access.py
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import PermissionDenied

from spaces.models import Space


def validate_space_access(space: Space, user: AbstractUser) -> None:
    if not user.is_active:
        raise PermissionDenied()
    access_granted = not space.restricted
    access_granted = access_granted or user.is_staff
    access_granted = access_granted or space.author == user
    access_granted = access_granted or (space.spacemember_set.filter(user=user).count() > 0)
    if not access_granted:
        raise PermissionDenied()

forum/spaces/views/view_members_mgmt.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect

from spaces.models import Space


@login_required
def view_space_leave(request, space_id: int):
    space = get_object_or_404(Space, id=space_id)
    if space.spacemember_set.filter(user=request.user).exists():
        space.member_remove(request.user)
    else:
        messages.info(request, f"You are not a member of {space.name}")
    return redirect("spaces:detail", space_id=space_id)


@login_required
def view_space_join(request, space_id: int):
    space = get_object_or_404(Space, id=space_id)
    if space.spacemember_set.filter(user=request.user).exists():
        messages.info(request, f"You are already a member of {space.name}")
    else:
        space.member_add(request.user)
    return redirect("spaces:detail", space_id=space_id)

forum/spaces/views/view_property_info.py
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import get_object_or_404, render

from spaces import models


@login_required
def view_property_info(request, property_name: str):
    if request.method != "GET":
        raise Http404()
    prop = get_object_or_404(models.SpaceProperty, name=property_name)

    return render(
        request,
        "spaces/property.single.template.html",
        {
            "property": prop,
            "spaces_count": prop.spaces.all().count(),
            "spaces": prop.spaces.all().order_by("-created_at"),
        },
    )

forum/spaces/views/view_space_edit.py
from datetime import datetime

from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render

from forum.models import Question
from spaces.apps import logger
from spaces.models import Space
from spaces.views.access import validate_space_access
from userauth.models import ForumUser


@login_required
def view_space_edit(request, space_id: int):
    space = get_object_or_404(Space, id=space_id)
    validate_space_access(space, request.user)
    is_member = space.spacemember_set.filter(user=request.user).exists()
    if request.method == "GET":
        member_usernames = ",".join(space.spacemember_set.all().values_list("user__username", flat=True))
        latest_posts = Question.objects.filter(space=space).order_by("-created_at")[:5]

        return render(
            request,
            "spaces/space-edit.html",
            {
                "space": space,
                "is_member": is_member,
                "member_usernames": member_usernames,
                "latest_posts": latest_posts,
            },
        )
    if request.method != "POST":
        logger.warning(f"User {request.user} performed unexpected request method: {request.method}")
        return redirect("spaces:detail", space_id=space_id)
    # Save changes
    data = request.POST.dict()
    if "startDate" in data and data.get("startDate") != "":
        try:
            start_date = datetime.fromisoformat(data.get("startDate")).date()
            space.start_date = start_date
        except ValueError:
            pass
    if "endDate" in data and data.get("endDate") != "":
        try:
            end_date = datetime.fromisoformat(data.get("endDate")).date()
            space.end_date = end_date
        except ValueError:
            pass
    members = data.get("members")
    if members:
        member_usernames = members.split(",")
        space.spacemember_set.exclude(user__username__in=member_usernames).delete()
        for username in member_usernames:
            user = ForumUser.objects.filter(username=username).first()
            if user is None:
                continue
            space.spacemember_set.get_or_create(user=user)
    space.page = data.get("page") or space.page
    space.save()
    return redirect("spaces:detail", space_id=space_id)

forum/spaces/views/view_space_info.py
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import render, get_object_or_404

from forum.models import Question
from spaces import models
from spaces.views.access import validate_space_access


@login_required
def view_space_info(request, space_id: int):
    if request.method != "GET":
        raise Http404()
    space = get_object_or_404(models.Space, id=space_id)
    validate_space_access(space, request.user)
    is_member = space.spacemember_set.filter(user=request.user).exists()
    members = space.spacemember_set.all()
    properties = space.properties.all()
    latest_posts = Question.objects.filter(space=space).order_by("-created_at")[:5]

    posts_count = Question.objects.filter(space=space).count()

    return render(
        request,
        "spaces/space-info.html",
        {
            "space": space,
            "is_member": is_member,
            "members": members,
            "latest_posts": latest_posts,
            "posts_count": posts_count,
            "properties": properties,
        },
    )

forum/spaces/views/view_space_questions.py
from constance import config
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import Http404
from django.shortcuts import get_object_or_404, render

from common import utils
from forum.models import Question
from forum.views.helpers import get_questions_queryset
from spaces.models import Space, SpaceMember
from spaces.views.access import validate_space_access
from wiwik_lib.utils import paginate_queryset


@login_required
def view_space_questions(request, space_id: int):
    if request.method != "GET":
        raise Http404()
    space = get_object_or_404(Space, id=space_id)
    validate_space_access(space, request.user)
    page_number = request.GET.get("page", 1)
    main_query = Question.objects.filter(space=space)
    properties = space.properties.all()
    page_qs = paginate_queryset(main_query, page_number, config.QUESTIONS_PER_PAGE)
    context = {
        "questions_list": page_qs,
        "header": f"Questions for space {space.short_name}",
        "space": space,
        "properties": properties,
        "can_edit_space": True,
    }
    return render(request, "spaces/space-questions.html", context)


@login_required
def view_user_spaces_latest_questions(request):
    user_spaces = (
        SpaceMember.objects.filter(user=request.user).values_list("space_id", flat=True).order_by("-created_at")[:3]
    )
    tab = utils.get_request_tab(request)
    q = utils.get_request_param(request, "q", None)
    tag_word = utils.get_request_param(request, "tag", None)
    spaces_base_qs = Question.objects.filter(space__in=user_spaces, space__restricted=True)
    if tag_word:
        spaces_base_qs = spaces_base_qs.filter(Q(tags__tag_word__iexact=tag_word))
    spaces_questions_qs = get_questions_queryset(spaces_base_qs, tab, q, None)
    spaces_questions_qs = spaces_questions_qs[:5]

    context = {
        "query": q,
        "has_results": spaces_questions_qs.count() > 0,
        "tag_word": tag_word,
        "space_questions": spaces_questions_qs,
    }
    return render(request, "spaces/includes/user-spaces-questions.partial.html", context)

forum/spaces/views/view_user_spaces.py
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import render

from forum.views import utils
from spaces.models import Space


@login_required
def view_side_menu_user_spaces(request):
    if request.method != "GET":
        raise Http404()
    if request.user.is_superuser:
        spaces = Space.objects.all().order_by("-created_at")
    else:
        spaces = Space.objects.filter(spacemember__user=request.user).order_by("-created_at")
    return render(
        request,
        "spaces/base.menu.spaces.partial.html",
        {
            "spaces": spaces,
            "calling_url": utils.get_request_param(request, "calling_url", None),
        },
    )

forum/spaces/templates/spaces/base.menu.spaces.partial.html
{% load spaces_tags %}
<hr/>
<li>
    Spaces
</li>
{% for space in spaces %}
    <li class="nav-item">
        <a class="nav-link {% if calling_url == space.url %}active{% endif %}"
           href="{% url 'spaces:questions' space.id %}">
            {% if space.logo %}
                <img src="{{ space.logo.url }}" alt="" height="25"/>
            {% endif %}
            {{ space.short_name }}
        </a>
    </li>
{% endfor %}

forum/spaces/templates/spaces/property.single.template.html
{% extends 'base.html' %}
{% load spaces_tags %}
{% load wiwik_template_tags %}
{% load humanize %}
{% block content %}
    <div class="row">
        <div class="col-xl-8 col-lg-9">
            <h1>{{ property.name }}</h1>
            <hr/>
            <p>
                Created
                {% if property.author %}
                    by {{ property.author.display_name }}
                {% endif %}
                at {{ property.created_at | absolute_date }}
            </p>
            <p>Exist in {{ spaces_count | intcomma }} spaces </p>
            <hr/>
            <div class="row">
                {% for item in spaces %}
                    <div class="col-6 mb-2">
                        <a href="{% url 'spaces:detail' item.id %}">
                            <h5>{{ item.name }}</h5>
                        </a>
                        <p>
                            {% if item.start_date and item.end_date %}
                                Active between <b>{{ item.start_date | absolute_date }}-
                                {{ item.end_date | absolute_date }}</b>.
                            {% elif item.start_date %}
                                Started <b>{{ item.start_date | timesince }}</b> ago.
                            {% else %}
                                Ongoing space.
                            {% endif %}
                            <br/>
                            Has <b>{{ item.spacemember_set.count }}</b> members
                            and <b>{{ item|questions_count }}</b> questions.
                        </p>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

forum/spaces/templates/spaces/space-edit.html
{% extends 'base.html' %}
{% load static compress wiwik_template_tags crispy_forms_tags %}
{% block extrastyle %}
    {{ block.super }}
    <link rel="stylesheet" href="{% tool_url 'easymde-css' %}">
    <link rel="stylesheet" href="{% tool_url 'bootstrap-datepicker-css' %}">
    <link href="{% static 'css/tagify.tags.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/tagify-customization.css' %}" rel="stylesheet" type="text/css"/>

{% endblock %}

{% block extrahead %}
    {#    <script src="{% static 'js/jquery.validate.min.js' %}"></script>#}
    <script src="{% tool_url 'tagify-js' %}"></script>
    <script src="{% tool_url 'tagify-polyfills-js' %}"></script>
    <script src="{% tool_url 'easymde-js' %}"></script>
    <script src="{% tool_url 'bootstrap-datepicker-js' %}"></script>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-8">
            <form method="post" id="spaceEditForm" class="group">
                <fieldset>
                    {% csrf_token %}
                    <legend class="border-bottom">
                        <strong>Editing space info for {{ space.name }}</strong>
                    </legend>

                    <h5>Space info</h5>
                    <div class="row my-2">
                        <div class="col-6">
                            <label for="startDateInput" class="form-label">Start date</label>
                            <div class="input-group date" data-provide="datepicker" data-date-format="yyyy-mm-dd">
                                <span class="material-icons">calendar_month</span>
                                <input id="startDateInput"
                                       name="startDate"
                                       type="text"
                                       class="form-control"
                                       value="{{ space.start_date | date:'Y-m-d' }}"/>
                                <div class="input-group-addon"></div>
                            </div>
                        </div>
                        <div class="col-6">
                            <label for="endDateInput" class="form-label">End date</label>
                            <div class="input-group date" data-provide="datepicker" data-date-format="yyyy-mm-dd">
                                <span class="material-icons">calendar_month</span>
                                <input id="endDateInput"
                                       name="endDate"
                                       type="text"
                                       class="form-control"
                                       value="{{ space.end_date | date:'Y-m-d' }}"/>
                                <div class="input-group-addon"></div>
                            </div>
                        </div>

                    </div>

                    <div>
                        <input id="usersList" class="users-list" name="members" style="width:100%"
                               value="{{ member_usernames }}">
                        {% compress js %}
                            <script src="{% static 'js/user-select-list.js' %}"></script>
                        {% endcompress %}
                    </div>

                    <textarea id="spacepage"
                              name="page">{{ space.page | default_if_none:"" }}</textarea>
                    {% include 'main/includes/easymde.template.html' with msg="Space info" el='spacepage' %}

                    <button style="width:100%" class="btn btn-primary mt-2 mb-2" type="submit">
                        Submit your changes
                    </button>
                </fieldset>
            </form>
        </div>
    </div>
    {#    <script>$("#tagForm").validate();</script>#}
{% endblock %}

forum/spaces/templates/spaces/space-info.html
{% extends 'base.html' %}
{% load userauth_tags %}
{% load wiwik_template_tags %}
{% load static %}

{% block extrahead %}
    <script src="{% static 'js/jquery.validate.min.js' %}"></script>
    <script src="{% tool_url 'easymde-js' %}"></script>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-8">
            <div class="border-bottom pb-2">
                <h2>
                    <strong>{{ space.name }}</strong> space page
                    <span class="pull-right">
                        {% if is_member %}
                            <a href="{% url 'spaces:edit' space.id %}"
                               class="btn btn-sm btn-outline-primary">
                                <span class="material-icons">edit_note</span>
                                Edit space info
                            </a>
                        {% endif %}
                    </span>
                </h2>
                <div class="pb-2">
                    {% if space.end_date %}
                        Active between {{ space.start_date | absolute_date }} -
                        {{ space.end_date | absolute_date }}
                    {% else %}
                        Started at {{ space.start_date | absolute_date }}
                    {% endif %}
                </div>
                <!-- space properties -->
                <div>
                    Properties
                    {% for property in properties %}
                        <a class="btn btn-space-property"
                           href="{% url 'spaces:property-info' property.name %}">
                            {{ property.name }}
                        </a>
                    {% endfor %}
                </div>
            </div>

            <div class="pb-2">
                <h5>Latest posts</h5>
                ({{ posts_count }} posts overall.
                <a href="{% url 'spaces:questions' space.id %}">View all posts</a>)
                {% if latest_posts %}
                    {% for item in latest_posts %}
                        <div class="row p-1">
                            <div class="col-2">
                                {{ item.created_at | date:"M d" }}
                            </div>
                            <div class="col-10">
                                <a href="{% url 'forum:thread' item.pk %}">
                                    <span class="badge {% class_for_votes item.votes %}"> {{ item.votes }} </span>
                                    {{ item.title }}
                                </a>
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
            <hr/>
            <div class="pb-2">
                {% if members %}
                    <h5>
                        Members
                        <span class="pull-right">
                            {% if is_member %}
                                <a href="{% url 'spaces:leave' space.id %}"
                                   class="btn btn-sm btn-outline-danger">
                                    <span class="material-icons">visibility_off</span>
                                    Leave space
                                </a>
                            {% else %}
                                <a href="{% url 'spaces:join' space.id %}"
                                   class="btn btn-sm btn-outline-primary">
                                    <span class="material-icons">visibility</span>
                                    Join space
                                </a>
                            {% endif %}
                        </span>
                    </h5>

                    <div class="row">
                        {% for member in members %}
                            <div class="col-6 mb-2">
                                {% include 'spaces/includes/user_card.template.html' with item=member %}
                            </div>
                        {% endfor %}
                    </div>
                {% else %}
                    Space has no active members.
                {% endif %}
            </div>
            <hr/>
            <h5>Space info</h5>
            <div class="mb-2">
                {% if space.page %}
                    {{ space.page | markdownify }}
                {% else %}
                    Page for space is empty, edit it...
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

forum/spaces/templates/spaces/space-questions.html
{% extends 'base.html' %}
{% load spaces_tags %}

{% block content %}
    <div class="row">
        <div class="col-12 col-lg-9">
            <div style="display: flex;justify-content: space-between;" class="p-2">
                <h2>Posts in space <b>{{ space.name }}</b></h2>
                <div>
                    <button onclick="location.href='{% url 'articles:create' %}'"
                            class="btn btn-primary btn-sm mb-1"
                            type="submit">
                        Propose article
                    </button>
                    <button onclick="location.href='{% url 'forum:ask' %}'"
                            class="btn btn-primary btn-sm"
                            type="submit">
                        Ask Question
                    </button>
                </div>
            </div>
            <div id="space-info" class="p-2">
                <div class="pull-right">
                    {% if space|ismember:user %}
                        <a href="{% url 'spaces:leave' space.id %}"
                           class="btn btn-sm btn-outline-danger">
                            <span class="material-icons">visibility_off</span>
                            Leave space
                        </a>
                    {% else %}
                        <a href="{% url 'spaces:join' space.id %}"
                           class="btn btn-sm btn-outline-primary">
                            <span class="material-icons">visibility</span>
                            Join space
                        </a>
                    {% endif %}
                    {% if can_edit_space %}
                        <a href="{% url 'spaces:detail' space.id %}"
                           class="btn btn-sm btn-outline-primary">
                            <span class="material-icons">edit_note</span>
                            View/Edit space info
                        </a>
                    {% endif %}
                </div>
                <div>
                    {% for property in space.properties %}
                        <a class="btn btn-space-property"
                           href="{% url 'spaces:property-info' property.name %}">
                            {{ property.name }}
                        </a>
                    {% endfor %}
                </div>
                <div>
                    Has <b>{{ space.spacemember_set.count }}</b> members
                    and <b>{{ space|questions_count }}</b> questions.
                </div>
            </div>


            <!-- Filter -->
            {% if tab %}
                <div class="row">
                    <nav>
                        <ul class="pagination pagination-md">
                            <li class="page-item {% if tab == TABS.LATEST.value %}active{% endif %}">
                                <a class="page-link" href="?tab={{ TABS.LATEST.value }}">Latest</a>
                            </li>
                            <li class="page-item {% if tab == TABS.MOST_VIEWED.value %}active{% endif %}">
                                <a class="page-link" href="?tab={{ TABS.MOST_VIEWED.value }}">Most viewed</a>
                            </li>
                            <li class="page-item {% if tab == TABS.UNANSWERED.value %}active{% endif %}">
                                <a class="page-link" href="?tab={{ TABS.UNANSWERED.value }}">Unanswered</a>
                            </li>
                            <li class="page-item {% if tab == TABS.UNRESOLVED.value %}active{% endif %}">
                                <a class="page-link" href="?tab={{ TABS.UNRESOLVED.value }}">Not resolved</a>
                            </li>
                        </ul>
                    </nav>
                </div>
            {% endif %}

            <div>
                <h3>Posts</h3>
                <div>
                    {% for q in questions_list %}
                        {% include "main/includes/questions.single-question.template.html" with q=q last=forloop.last %}
                    {% endfor %}
                </div>
            </div>
            <div class="pull-right">
                {% include 'main/includes/questions.pagination.template.html' with items_list=questions_list %}
            </div>
        </div>
    </div>
{% endblock %}