forum/forum/urls.py
from django.urls import path

from . import views
from .views.feed import LatestEntriesFeed

urlpatterns = [
    path("", views.view_home, name="home"),
    path("questions/", views.view_questions, name="list"),
    path("questions/tag/<str:tag_word>/", views.view_tag_questions_list, name="tag"),
    path("questions/<int:pk>/", views.view_single_question, name="thread"),
    path("questions/ask", views.view_askquestion, name="ask"),
    path("question/<int:pk>/edit", views.view_editquestion, name="question_edit"),
    path(
        "questions/answer/<int:answer_pk>/edit",
        views.view_editanswer,
        name="answer_edit",
    ),
    path("question/<int:pk>/delete", views.view_delete_question, name="question_delete"),
    path(
        "question/<int:question_pk>/delete/<int:answer_pk>",
        views.view_delete_answer,
        name="answer_delete",
    ),
]
# Partials
urlpatterns += [
    path(
        "questions/<int:question_pk>/tags",
        views.view_partial_question_tags,
        name="question_tags",
    ),
    path(
        "<str:post_type>/<int:post_pk>/comments",
        views.view_partial_post_comments,
        name="post_comments",
    ),
    path(
        "questions/<int:question_pk>/invites",
        views.view_partial_invites,
        name="questions_invites",
    ),
    path("users/navbar", views.view_partial_user_navbar, name="user_navbar"),
    path("similar-questions/", views.view_similar_questions, name="similar"),
    path("tags/<int:pk>/popover", views.view_partial_tag_popover, name="tag_popover"),
]
# Actions
urlpatterns += [
    path("question/<int:pk>/follow/", views.view_follow_question, name="follow"),
    path("question/<int:pk>/unfollow/", views.view_unfollow_question, name="unfollow"),
    path(
        "question/<int:question_pk>/bookmark",
        views.view_bookmark_question,
        name="bookmark",
    ),
    path(
        "question/<int:question_pk>/unbookmark",
        views.view_unbookmark_question,
        name="unbookmark",
    ),
    path("usertags/<str:tag_word>/watch", views.view_user_follow_tag, name="watch_tag"),
    path(
        "usertags/<str:tag_word>/unwatch",
        views.view_user_unfollow_tag,
        name="unwatch_tag",
    ),
    path(
        "question/<int:question_pk>/invite_to_question",
        views.view_invite_to_question,
        name="invite",
    ),
    path(
        "question/<int:question_pk>/download_markdown",
        views.view_download_thread,
        name="markdown",
    ),
    path(
        "question/<int:pk>/upvote_comment/<str:parent_model_name>/<int:comment_pk>",
        views.view_upvote_comment,
        name="comment_upvote",
    ),
    path(
        "question/<int:pk>/delete_comment/<str:model>/<int:comment_id>",
        views.view_deletecomment,
        name="comment_delete",
    ),
]
# Automatic actions
urlpatterns += [
    path(
        "question/<int:pk>/upvote/<str:model_name>/<int:model_pk>",
        views.view_upvote,
        name="upvote",
    ),
    path(
        "question/<int:pk>/downvote/<str:model_name>/<int:model_pk>",
        views.view_downvote,
        name="downvote",
    ),
    path(
        "mark_as_seen/<int:vote_activity_pk>/",
        views.view_mark_as_seen,
        name="mark_seen",
    ),
    path("mark_all_as_seen/", views.view_all_mark_as_seen, name="mark_all_seen"),
    path(
        "question/<int:question_pk>/accept/<int:answer_pk>",
        views.view_acceptanswer,
        name="answer_accept",
    ),
]

urlpatterns += [
    path("users-autocomplete/", views.view_users_autocomplete, name="users_autocomplete"),
    path("users-get/", views.view_get_users_data, name="users-get"),
    path("image-upload/", views.view_image_upload, name="image_upload"),
]
# Slack
urlpatterns += [
    path("integrations/slack_post/", views.view_slack_post, name="slack-post"),
    path(
        "integrations/tags_autocomplete/",
        views.view_tags_autocomplete_for_slack,
        name="slack-tags-autocomplete",
    ),
    path("integrations/slack_search/", views.search_from_slack, name="slack-search"),
]

# RSS
urlpatterns += [
    path("rss/feed/", LatestEntriesFeed()),
    path("editing-help/", views.view_markdown_help),
]

# One time code
from wiwik_lib.templatetags.wiwik_template_tags import check_latex_config  # noqa: E402
from forum.integrations.slack_api import configure_slack_client  # noqa: E402

check_latex_config()
configure_slack_client()

forum/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include(("forum.urls", "forum"), namespace="forum")),
    path("articles/", include(("articles.urls", "articles"), namespace="articles")),
    path("BB-aDmin/", admin.site.urls),  # intentionally non-standard to prevent casual hacking tries.
    path("scheduler/", include("scheduler.urls")),
    path("accounts/", include("allauth.urls")),
    path("users/", include(("userauth.urls", "userauth"), namespace="userauth")),
    path("badges/", include(("badges.urls", "badges"), namespace="badges")),
    path("tags/", include(("tags.urls", "tags"), namespace="tags")),
    path("general/", include(("wiwik_lib.urls", "wiwik_lib"), namespace="general")),
    path("spaces/", include(("spaces.urls", "spaces"), namespace="spaces")),
    path(
        "similarity/",
        include(("similarity.urls", "similarity"), namespace="similarity"),
    ),
]

if settings.DEBUG_TOOLS:
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

forum/spaces/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("user-spaces", views.view_side_menu_user_spaces, name="user-spaces"),
    path("<str:space_id>/info", views.view_space_info, name="detail"),
    path("<int:space_id>/edit", views.view_space_edit, name="edit"),
    path("<str:space_id>/leave", views.view_space_leave, name="leave"),
    path("<str:space_id>/join", views.view_space_join, name="join"),
    path("<str:space_id>/questions", views.view_space_questions, name="questions"),
    path(
        "latest-questions",
        views.view_user_spaces_latest_questions,
        name="user-spaces-questions",
    ),
    path("property/<str:property_name>", views.view_property_info, name="property-info"),
]

forum/userauth/urls.py
from django.urls import path, re_path

from . import views
from .admin import SendUserEmails

urlpatterns = [
    path("signup/", views.view_signup, name="signup"),
    path("login/", views.view_login, name="login"),
    path("logout/", views.view_logout, name="logout"),
    path(
        "staff-deactivate/<str:username>/",
        views.view_deactivate_user,
        name="deactivate_user",
    ),
    path("staff-activate/<str:username>/", views.view_activate_user, name="activate_user"),
    path("editprofile/", views.view_editprofile, name="edit"),
    path("editprofile/profile-pic/", views.view_profile_pic, name="profile_pic"),
    path("profile/<str:username>/<str:tab>/", views.view_profile, name="profile"),
    re_path(
        r"^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]+)/$",
        views.view_activate,
        name="activate",
    ),
    path("", views.view_users, name="list"),
    path("query/", views.view_users_query, name="list_query"),
    re_path(
        r"^unsubscribe/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]+)/$",
        views.view_unsubscribe,
        name="unsubscribe",
    ),
    path("email-users/", SendUserEmails.as_view(), name="admin_email"),
]

forum/forum/models/drafts.py
from .base import Question


class Draft(Question):
    pass

forum/forum/models/stats.py
from django.conf import settings
from django.db import models

from wiwik_lib.advanced_model_manager import AdvancedModelManager
from wiwik_lib.models import user_model_defer_fields


class UserTagStats(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    tag = models.ForeignKey("tags.Tag", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    updated_at = models.DateTimeField(auto_now=True)
    questions_by_user = models.IntegerField(
        default=0,
        help_text="Number of questions authored by user in the tag",
    )
    answers_by_user = models.IntegerField(
        default=0,
        help_text="Number of answers authored by user in the tag",
    )
    reputation = models.IntegerField(default=0, help_text="Reputation earned by user for tag")
    reputation_last_month = models.IntegerField(
        default=0,
        help_text="Reputation earned by user for tag in the past month",
    )
    objects = AdvancedModelManager(
        select_related=(
            "user",
            "tag",
        ),
        deferred_fields=user_model_defer_fields("user"),
    )

    def __str__(self):
        return (
            f"UserTagStats[{self.user.username} - {self.tag.tag_word}] "
            f"#q={self.questions_by_user}, #a={self.answers_by_user}, "
            f"rep={self.reputation}, rep_month={self.reputation_last_month}"
        )

forum/forum/views/common.py
from django.urls import reverse

from wiwik_lib import utils


def get_model_url(model_name: str, model) -> str:
    if model_name == "tag":
        return reverse("forum:tag", args=[model.tag_word])
    if model_name == "comment_answer":
        parent_model_name = "answer"
        parent_pk = model.answer.pk
    elif model_name == "answer":
        parent_model_name = "answer"
        parent_pk = model.pk
    elif model_name == "comment_question":
        parent_model_name = "question"
        parent_pk = model.question.pk
    else:
        parent_model_name = "question"
        parent_pk = model.pk
    anchor = f"#{parent_model_name}_{parent_pk}"
    return reverse("forum:thread", args=[model.get_question().pk]) + anchor


def get_model_url_with_base(model_name: str, model) -> str:
    return utils.CURRENT_SITE + get_model_url(model_name, model)

forum/forum/views/feed.py
from django.contrib.syndication.views import Feed
from django.urls import reverse

from forum.models import Question


class LatestEntriesFeed(Feed):
    title = "Latest questions on wiwik"
    link = "/rss/feed/"
    description = "Latest questions on wiwik"
    description_template = "main/rss.feed.description.html"

    def items(self):
        return Question.objects.order_by("-created_at")[:30]

    def item_title(self, item):
        return item.title

    # item_link is only needed if NewsItem has no get_absolute_url method.
    def item_link(self, item):
        return reverse("forum:thread", args=[item.pk])

    def item_pubdate(self, item):
        return item.created_at

    def item_author_name(self, item: Question):
        return item.author.display_name()

    def item_author_link(self, item: Question):
        return reverse("userauth:profile", args=[item.author.username, "questions"])

forum/forum/views/follow_models.py
from datetime import timedelta

from django.contrib.auth.models import AbstractUser
from django.db.models import Sum
from django.utils import timezone

from forum import models
from tags.models import Tag
from tags.utils import update_tag_stats_for_tag
from wiwik_lib.views.follow_views import create_follow, delete_follow


def handle_user_tag_stats(tag: Tag, user: AbstractUser) -> None:
    questions_by_user = models.Question.objects.filter(author=user, tags=tag).count()
    answers_by_user = models.Answer.objects.filter(author=user, question__tags=tag).count()
    reputation = (
        models.VoteActivity.objects.filter(target=user, question__tags=tag)
        .aggregate(rep=Sum("reputation_change"))
        .get("rep")
        or 0
    )
    last_month = timezone.now() - timedelta(days=30)
    reputation_last_month = (
        models.VoteActivity.objects.filter(
            target=user,
            question__tags=tag,
            created_at__gte=last_month,
        )
        .aggregate(rep=Sum("reputation_change"))
        .get("rep")
        or 0
    )

    # Only if any number is bigger than 0, then stats object should be created
    should_have_stats = any((questions_by_user, answers_by_user, reputation, reputation_last_month))

    if not should_have_stats:
        models.UserTagStats.objects.filter(tag=tag, user=user).delete()
        return

    stats, _ = models.UserTagStats.objects.get_or_create(tag=tag, user=user)
    stats.questions_by_user = questions_by_user
    stats.answers_by_user = answers_by_user
    stats.reputation = reputation
    stats.reputation_last_month = reputation_last_month
    stats.save()
    update_tag_stats_for_tag(stats.tag)


def create_follow_tag(tag: Tag, user: AbstractUser) -> None:
    handle_user_tag_stats(tag, user)
    create_follow(tag, user)


def delete_follow_tag(tag: Tag, user: AbstractUser) -> None:
    handle_user_tag_stats(tag, user)
    delete_follow(tag, user)

forum/forum/views/helpers.py
import time
from typing import Optional

from constance import config
from django.contrib.auth.models import AbstractUser
from django.db.models import QuerySet
from django.shortcuts import render

from common import utils
from common.utils import TabEnum
from forum import jobs
from forum.jobs.others import log_search
from forum.models import Question
from forum.views import search
from spaces.models import Space
from userauth.models import ForumUser
from wiwik_lib.models import user_model_defer_fields
from wiwik_lib.utils import paginate_queryset


def get_questions_queryset(
    base_queryset: QuerySet,
    tab: Optional[str],
    query: Optional[str],
    user: Optional[AbstractUser],
) -> QuerySet:
    base_queryset = base_queryset.select_related(
        "author",
    ).defer(*user_model_defer_fields("author"), "source", "source_id", "link")
    start_time = time.time()
    if query is not None:
        qs = search.query_method(base_queryset, query)
    elif tab == TabEnum.MOST_VIEWED.value:
        qs = base_queryset.all().order_by("-views")
    elif tab == TabEnum.UNRESOLVED.value:
        qs = base_queryset.filter(type__in=Question.POST_TYPE_ACCEPTING_ANSWERS, has_accepted_answer=False).order_by(
            "-created_at"
        )
    elif tab == TabEnum.UNANSWERED.value:
        qs = base_queryset.filter(type__in=Question.POST_TYPE_ACCEPTING_ANSWERS, answers_count=0).order_by(
            "-created_at"
        )
    else:
        qs = base_queryset.all().order_by("-type", "-created_at")
    if query and user:
        mstaken = int((time.time() - start_time) * 1000)
        first_five = list(qs.values_list("id", flat=True)[:5])
        jobs.start_job(log_search, user, query, first_five, mstaken)
    return qs


def get_restricted_space_ids(user: ForumUser) -> list[int]:
    return list(Space.objects.filter(restricted=True).values_list("id", flat=True))


def render_questions(request, base_qs: QuerySet, header: str, extra: dict = None):
    tab = utils.get_request_tab(request)
    q = utils.get_request_param(request, "q", None)
    restricted_spaces = get_restricted_space_ids(request.user)
    all_questions_qs = get_questions_queryset(base_qs.exclude(space_id__in=restricted_spaces), tab, q, request.user)
    all_questions_qs = all_questions_qs.prefetch_related(
        "tags",
    )
    page_number = int(utils.get_request_param(request, "page", "1"))
    page_qs = paginate_queryset(all_questions_qs, page_number, config.QUESTIONS_PER_PAGE)
    context = {
        "all_questions": page_qs,
        "tab": tab if q is None else None,
        "header": header,
        "tag_watched": None,
    }
    if q:
        context["query"] = q
    if extra is not None:
        context = context | extra
    return render(request, "main/questions.html", context)

forum/forum/views/view_partial_user_navbar.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render


@login_required
def view_partial_user_navbar(request):
    return render(
        request,
        "partial.user.navbar.html",
    )

forum/forum/views/view_user_tags.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.urls import reverse, resolve

from forum.views.follow_models import delete_follow_tag, create_follow_tag
from tags.apps import logger
from tags.models import Tag


def _parse_redirect_url(request, tag_word: str) -> str:
    redirect_url = request.META.get("HTTP_REFERER", None) or reverse(
        "forum:tag",
        args=[
            tag_word,
        ],
    )
    try:
        resolve(redirect_url)
    except Exception:
        logger.warning(f"Bad redirect url: {redirect_url}")
        redirect_url = reverse(
            "forum:tag",
            args=[
                tag_word,
            ],
        )
    return redirect_url


@login_required
def view_user_follow_tag(request, tag_word: str):
    redirect_url = request.META.get("HTTP_REFERER", None) or reverse(
        "forum:tag",
        args=[
            tag_word,
        ],
    )
    tag = Tag.objects.filter(tag_word=tag_word).first()
    if tag is None:
        return redirect("forum:tag", tag_word=tag_word)
    create_follow_tag(tag, request.user)
    return redirect(redirect_url)


@login_required
def view_user_unfollow_tag(request, tag_word: str):
    redirect_url = _parse_redirect_url(request, tag_word)
    tag = Tag.objects.filter(tag_word=tag_word).first()
    if tag is None:
        return redirect("forum:tag", tag_word=tag_word)
    delete_follow_tag(tag, request.user)
    return redirect(redirect_url)

forum/forum/templates/includes/base.google-analytics.html
<!-- Global site tag (gtag.js) - Google Analytics -->
{% if config.GOOGLE_ANALYTICS_KEY %}
    <script async src="https://www.googletagmanager.com/gtag/js?id={{ config.GOOGLE_ANALYTICS_KEY }}"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }

        gtag('js', new Date());
        gtag('config', '{{ config.GOOGLE_ANALYTICS_KEY }}');
    </script>
{% endif %}

forum/forum/templates/includes/base.menu.html
{% load wiwik_template_tags %}
<div>
    <ul class="nav flex-column">
        <li class="nav-item">
            <a class="nav-link {% if request.path == '/' %}active{% endif %}" href="/">
                <span class="material-icons">home</span> Home
            </a>
        </li>
        <hr/>
        <li class="nav-item">
            <a class="nav-link {% if request.path|startswith:'/question' %}active{% endif %}"
               href="{% url 'forum:list' %}">
                <span class="material-icons">contact_support</span> Posts
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if request.path|startswith:'/articles' %}active{% endif %}"
               href="{% url 'articles:list' %}">
                <span class="material-icons">article</span> Articles
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if request.path|startswith:'/tags/' or request.path == '/synonyms/' %}active{% endif %}"
               href="{% url 'tags:list' %}">
                <span class="material-icons">style</span> Tags
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if request.path|startswith:'/users' %}active{% endif %}"
               href="{% url 'userauth:list' %}">
                <span class="material-icons">people</span> Users
            </a>
        </li>
        <div hx-get="{% url 'spaces:user-spaces' %}?calling_url={{ request.path }}"
             hx-trigger="load" hx-swap="outerHTML"></div>
    </ul>
</div>

forum/forum/templates/includes/messages.html
{% if messages %}
    <div class="messages">
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                {{ message | safe }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    </div>
    <script type="text/javascript">
        $(".alert").delay(3000).slideUp(200, function () {
            $(this).alert('close');
        });
    </script>
{% endif %}

forum/forum/templates/includes/partial.user.navbar.html
{% load static %}
{% load userauth_tags compress humanize %}
<a class="nav-item nav-link"
   href="{% url 'userauth:profile' user.username 'questions' %}">
    <img style="height: 25px;border-radius: 50%;" src="{{ user.profile_pic.url }}"
         alt="" onerror="this.onerror=null; this.src='/media/default_pics/no_pic.jpg'"/>
    <span>
    <b><span class="material-icons">emoji_events</span>{{ user.reputation_score | intcomma }}</b>
    {% include 'includes/user-badges.html' with user=user %}
    </span>
</a>
<div class="nav-item nav-link dropdown">
    <a class="menu-icon-link" href="#"
       hx-get="{% url 'forum:mark_all_seen' %}"
       hx-trigger="click"
       hx-target="#reputation-badge"
       id="navbarDropdownReputation"
       role="button" data-bs-toggle="dropdown"
       aria-expanded="false">
        <span class="material-icons">trending_up</span>
        <span id="reputation-badge">
           {% if user|unseen_reputation_sum > 0 %}
               <span class="menutoggle-badge">{{ user|unseen_reputation_sum }}</span>
           {% endif %}
       </span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end"
        style="width: 363px;max-height: 390px;overflow-y: auto;"
        aria-labelledby="navbarDropdownReputation">
        {% if not user.reputation_votes %}
            <li class="dropdown-item disabled">No reputation earned, start asking and answering</li>
        {% else %}
            <li class="dropdown-item disabled ">
                Achievements
                <a class="pull-right pointer-event" href="{% url 'badges:list' %}">badges</a>
            </li>
            {% regroup user|latest_reputation by time_section as time_sections %}
            {% for time_section in time_sections %}
                <li class="dropdown-item disabled mt-2">
                    {{ time_section.grouper }}
                </li>
                {% for item in time_section.list %}
                    {% if item.badge_id %}
                        <a class="text-wrap list-group-item dropdown-item {% if not item.seen %}bg-unseen{% endif %}"
                           href="{% url 'userauth:profile' item.target.username 'badges' %}">
                            <div class="row m-1">
                                <div class="col-1">
                                    <span class="material-icons text-{{ item.badge.type }}">verified</span>
                                </div>
                                <div class="col-11">
                                    You've earned the "{{ item.badge.name }}" badge ({{ item.badge.description }})
                                </div>
                            </div>
                        </a>
                    {% else %}
                        <a class="text-wrap list-group-item dropdown-item {% if not item.seen %}list-group-item-unseen{% endif %}"
                           href="{% url 'forum:thread' item.question_id %}">
                            <div class="row m-1">
                                <div class="col-1"
                                     style="color: {% if item.reputation_change > 0 %}forestgreen{% else %}darkred{% endif %};">
                                    {% if item.reputation_change > 0 %}+{% endif %}{{ item.reputation_change }}
                                </div>
                                <div class="col-11">
                                    {{ item.question.title }}
                                </div>
                            </div>
                        </a>
                    {% endif %}
                {% endfor %}
            {% endfor %}
            {% if user.reputation_votes.count > MAX_REPUTATION_ITEMS %}
                {# TODO performance improvement - move count to user_additionaldata #}
                <a class="list-group-item dropdown-item"
                   href="{% url 'userauth:profile' user.username 'reputation' %}">
                    Show more...
                </a>
            {% endif %}
        {% endif %}
    </ul>
</div>
<div class="nav-item nav-link dropdown">
    <a class="menu-icon-link" href="#" id="navbarDropdownBookmarks"
       role="button" data-bs-toggle="dropdown" aria-expanded="false">
        <span class="material-icons">bookmarks</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end"
        style="width: 363px;"
        aria-labelledby="navbarDropdownBookmarks">
        {% if user.bookmarks %}
            <li class="dropdown-item disabled">
                No bookmarks
                <div>
                    Bookmark posts so you can access them faster from here
                </div>
            </li>
        {% else %}
            <li class="dropdown-item disabled">Bookmarks</li>
            {% for bookmark in user|latest_bookmarks %}
                <a class="text-wrap list-group-item dropdown-item"
                   href="{% url 'forum:thread' bookmark.question.pk %}">
                    <div class="row m-1">
                        <div class="col-1">
                            <span class="badge {% class_for_votes bookmark.question.votes %}">
                                {{ bookmark.question.votes }}
                            </span>
                        </div>
                        <div class="col-11">
                            {{ bookmark.question.title }}
                        </div>
                    </div>
                </a>
            {% endfor %}
            {% if user.additional_data.bookmarks_count > MAX_BOOKMARK_ITEMS %}
                <a class="list-group-item dropdown-item"
                   href="{% url 'userauth:profile' user.username 'bookmarks' %}">
                    Show more...
                </a>
            {% endif %}
        {% endif %}
    </ul>
</div>

forum/forum/templates/includes/user-badges.html
{% load static %}
{% load humanize %}
{# Badges info #}
<span>
{% if user.gold_badges %}
    <span class="mx-1 text-gold">
        <span class="material-icons">verified</span>
        {{ user.gold_badges | intcomma }}
    </span>
{% endif %}
    {% if user.silver_badges %}
        <span class="mx-1 text-silver">
        <span class="material-icons">verified</span>
        {{ user.silver_badges | intcomma }}
    </span>
    {% endif %}
    {% if user.bronze_badges %}
        <span class="mx-1 text-bronze">
        <span class="material-icons">verified</span>
        {{ user.bronze_badges | intcomma }}
    </span>
    {% endif %}
</span>

forum/forum/templates/includes/user.navbar.html
{% if user.is_authenticated %}
    <div class="navbar-nav"
         hx-get="{% url 'forum:user_navbar' %}"
         hx-trigger="load, every 60s"></div>
{% else %}
    <a class="nav-item nav-link" href="{% url 'userauth:login' %}"><strong>Login</strong></a>
    <a class="nav-item nav-link" href="{% url 'userauth:signup' %}"><strong>Register</strong></a>
{% endif %}