forum/articles/urls.py
from django.urls import path

from . import views

# Articles
urlpatterns = [
    path("", views.view_article_list, name="list"),
    path("<int:pk>/", views.view_article_detail, name="detail"),
    path("create/", views.view_article_create, name="create"),
    path("<int:pk>/edit/", views.view_article_edit, name="edit"),
    path("<int:pk>/delete/", views.view_article_delete, name="delete"),
]

forum/forum/urls.py
from django.urls import path

from . import views
from .views.feed import LatestEntriesFeed

urlpatterns = [
    path("", views.view_home, name="home"),
    path("questions/", views.view_questions, name="list"),
    path("questions/tag/<str:tag_word>/", views.view_tag_questions_list, name="tag"),
    path("questions/<int:pk>/", views.view_single_question, name="thread"),
    path("questions/ask", views.view_askquestion, name="ask"),
    path("question/<int:pk>/edit", views.view_editquestion, name="question_edit"),
    path(
        "questions/answer/<int:answer_pk>/edit",
        views.view_editanswer,
        name="answer_edit",
    ),
    path("question/<int:pk>/delete", views.view_delete_question, name="question_delete"),
    path(
        "question/<int:question_pk>/delete/<int:answer_pk>",
        views.view_delete_answer,
        name="answer_delete",
    ),
]
# Partials
urlpatterns += [
    path(
        "questions/<int:question_pk>/tags",
        views.view_partial_question_tags,
        name="question_tags",
    ),
    path(
        "<str:post_type>/<int:post_pk>/comments",
        views.view_partial_post_comments,
        name="post_comments",
    ),
    path(
        "questions/<int:question_pk>/invites",
        views.view_partial_invites,
        name="questions_invites",
    ),
    path("users/navbar", views.view_partial_user_navbar, name="user_navbar"),
    path("similar-questions/", views.view_similar_questions, name="similar"),
    path("tags/<int:pk>/popover", views.view_partial_tag_popover, name="tag_popover"),
]
# Actions
urlpatterns += [
    path("question/<int:pk>/follow/", views.view_follow_question, name="follow"),
    path("question/<int:pk>/unfollow/", views.view_unfollow_question, name="unfollow"),
    path(
        "question/<int:question_pk>/bookmark",
        views.view_bookmark_question,
        name="bookmark",
    ),
    path(
        "question/<int:question_pk>/unbookmark",
        views.view_unbookmark_question,
        name="unbookmark",
    ),
    path("usertags/<str:tag_word>/watch", views.view_user_follow_tag, name="watch_tag"),
    path(
        "usertags/<str:tag_word>/unwatch",
        views.view_user_unfollow_tag,
        name="unwatch_tag",
    ),
    path(
        "question/<int:question_pk>/invite_to_question",
        views.view_invite_to_question,
        name="invite",
    ),
    path(
        "question/<int:question_pk>/download_markdown",
        views.view_download_thread,
        name="markdown",
    ),
    path(
        "question/<int:pk>/upvote_comment/<str:parent_model_name>/<int:comment_pk>",
        views.view_upvote_comment,
        name="comment_upvote",
    ),
    path(
        "question/<int:pk>/delete_comment/<str:model>/<int:comment_id>",
        views.view_deletecomment,
        name="comment_delete",
    ),
]
# Automatic actions
urlpatterns += [
    path(
        "question/<int:pk>/upvote/<str:model_name>/<int:model_pk>",
        views.view_upvote,
        name="upvote",
    ),
    path(
        "question/<int:pk>/downvote/<str:model_name>/<int:model_pk>",
        views.view_downvote,
        name="downvote",
    ),
    path(
        "mark_as_seen/<int:vote_activity_pk>/",
        views.view_mark_as_seen,
        name="mark_seen",
    ),
    path("mark_all_as_seen/", views.view_all_mark_as_seen, name="mark_all_seen"),
    path(
        "question/<int:question_pk>/accept/<int:answer_pk>",
        views.view_acceptanswer,
        name="answer_accept",
    ),
]

urlpatterns += [
    path("users-autocomplete/", views.view_users_autocomplete, name="users_autocomplete"),
    path("users-get/", views.view_get_users_data, name="users-get"),
    path("image-upload/", views.view_image_upload, name="image_upload"),
]
# Slack
urlpatterns += [
    path("integrations/slack_post/", views.view_slack_post, name="slack-post"),
    path(
        "integrations/tags_autocomplete/",
        views.view_tags_autocomplete_for_slack,
        name="slack-tags-autocomplete",
    ),
    path("integrations/slack_search/", views.search_from_slack, name="slack-search"),
]

# RSS
urlpatterns += [
    path("rss/feed/", LatestEntriesFeed()),
    path("editing-help/", views.view_markdown_help),
]

# One time code
from wiwik_lib.templatetags.wiwik_template_tags import check_latex_config  # noqa: E402
from forum.integrations.slack_api import configure_slack_client  # noqa: E402

check_latex_config()
configure_slack_client()

forum/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include(("forum.urls", "forum"), namespace="forum")),
    path("articles/", include(("articles.urls", "articles"), namespace="articles")),
    path("BB-aDmin/", admin.site.urls),  # intentionally non-standard to prevent casual hacking tries.
    path("scheduler/", include("scheduler.urls")),
    path("accounts/", include("allauth.urls")),
    path("users/", include(("userauth.urls", "userauth"), namespace="userauth")),
    path("badges/", include(("badges.urls", "badges"), namespace="badges")),
    path("tags/", include(("tags.urls", "tags"), namespace="tags")),
    path("general/", include(("wiwik_lib.urls", "wiwik_lib"), namespace="general")),
    path("spaces/", include(("spaces.urls", "spaces"), namespace="spaces")),
    path(
        "similarity/",
        include(("similarity.urls", "similarity"), namespace="similarity"),
    ),
]

if settings.DEBUG_TOOLS:
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

forum/spaces/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("user-spaces", views.view_side_menu_user_spaces, name="user-spaces"),
    path("<str:space_id>/info", views.view_space_info, name="detail"),
    path("<int:space_id>/edit", views.view_space_edit, name="edit"),
    path("<str:space_id>/leave", views.view_space_leave, name="leave"),
    path("<str:space_id>/join", views.view_space_join, name="join"),
    path("<str:space_id>/questions", views.view_space_questions, name="questions"),
    path(
        "latest-questions",
        views.view_user_spaces_latest_questions,
        name="user-spaces-questions",
    ),
    path("property/<str:property_name>", views.view_property_info, name="property-info"),
]

forum/tags/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.view_home, name="list"),
    path("query/", views.view_query, name="list_query"),
    path("<str:tag_word>/edit", views.view_edit_tag, name="edit"),
    path("<str:tag_word>/info", views.view_tag_info, name="info"),
    path(
        "tags-autocomplete/",
        views.view_tags_autocomplete,
        name="autocomplete",
    ),
    path("synonyms/", views.view_synonym_list, name="synonyms_list"),
    path(
        "synonyms/approve/<int:synonym_pk>",
        views.view_approve_synonym,
        name="synonyms_approve",
    ),
]

forum/userauth/urls.py
from django.urls import path, re_path

from . import views
from .admin import SendUserEmails

urlpatterns = [
    path("signup/", views.view_signup, name="signup"),
    path("login/", views.view_login, name="login"),
    path("logout/", views.view_logout, name="logout"),
    path(
        "staff-deactivate/<str:username>/",
        views.view_deactivate_user,
        name="deactivate_user",
    ),
    path("staff-activate/<str:username>/", views.view_activate_user, name="activate_user"),
    path("editprofile/", views.view_editprofile, name="edit"),
    path("editprofile/profile-pic/", views.view_profile_pic, name="profile_pic"),
    path("profile/<str:username>/<str:tab>/", views.view_profile, name="profile"),
    re_path(
        r"^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]+)/$",
        views.view_activate,
        name="activate",
    ),
    path("", views.view_users, name="list"),
    path("query/", views.view_users_query, name="list_query"),
    re_path(
        r"^unsubscribe/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]+)/$",
        views.view_unsubscribe,
        name="unsubscribe",
    ),
    path("email-users/", SendUserEmails.as_view(), name="admin_email"),
]

forum/forum/models/drafts.py
from .base import Question


class Draft(Question):
    pass

forum/forum/views/common.py
from django.urls import reverse

from wiwik_lib import utils


def get_model_url(model_name: str, model) -> str:
    if model_name == "tag":
        return reverse("forum:tag", args=[model.tag_word])
    if model_name == "comment_answer":
        parent_model_name = "answer"
        parent_pk = model.answer.pk
    elif model_name == "answer":
        parent_model_name = "answer"
        parent_pk = model.pk
    elif model_name == "comment_question":
        parent_model_name = "question"
        parent_pk = model.question.pk
    else:
        parent_model_name = "question"
        parent_pk = model.pk
    anchor = f"#{parent_model_name}_{parent_pk}"
    return reverse("forum:thread", args=[model.get_question().pk]) + anchor


def get_model_url_with_base(model_name: str, model) -> str:
    return utils.CURRENT_SITE + get_model_url(model_name, model)

forum/forum/views/feed.py
from django.contrib.syndication.views import Feed
from django.urls import reverse

from forum.models import Question


class LatestEntriesFeed(Feed):
    title = "Latest questions on wiwik"
    link = "/rss/feed/"
    description = "Latest questions on wiwik"
    description_template = "main/rss.feed.description.html"

    def items(self):
        return Question.objects.order_by("-created_at")[:30]

    def item_title(self, item):
        return item.title

    # item_link is only needed if NewsItem has no get_absolute_url method.
    def item_link(self, item):
        return reverse("forum:thread", args=[item.pk])

    def item_pubdate(self, item):
        return item.created_at

    def item_author_name(self, item: Question):
        return item.author.display_name()

    def item_author_link(self, item: Question):
        return reverse("userauth:profile", args=[item.author.username, "questions"])

forum/forum/views/follow_models.py
from datetime import timedelta

from django.contrib.auth.models import AbstractUser
from django.db.models import Sum
from django.utils import timezone

from forum import models
from tags.models import Tag
from tags.utils import update_tag_stats_for_tag
from wiwik_lib.views.follow_views import create_follow, delete_follow


def handle_user_tag_stats(tag: Tag, user: AbstractUser) -> None:
    questions_by_user = models.Question.objects.filter(author=user, tags=tag).count()
    answers_by_user = models.Answer.objects.filter(author=user, question__tags=tag).count()
    reputation = (
        models.VoteActivity.objects.filter(target=user, question__tags=tag)
        .aggregate(rep=Sum("reputation_change"))
        .get("rep")
        or 0
    )
    last_month = timezone.now() - timedelta(days=30)
    reputation_last_month = (
        models.VoteActivity.objects.filter(
            target=user,
            question__tags=tag,
            created_at__gte=last_month,
        )
        .aggregate(rep=Sum("reputation_change"))
        .get("rep")
        or 0
    )

    # Only if any number is bigger than 0, then stats object should be created
    should_have_stats = any((questions_by_user, answers_by_user, reputation, reputation_last_month))

    if not should_have_stats:
        models.UserTagStats.objects.filter(tag=tag, user=user).delete()
        return

    stats, _ = models.UserTagStats.objects.get_or_create(tag=tag, user=user)
    stats.questions_by_user = questions_by_user
    stats.answers_by_user = answers_by_user
    stats.reputation = reputation
    stats.reputation_last_month = reputation_last_month
    stats.save()
    update_tag_stats_for_tag(stats.tag)


def create_follow_tag(tag: Tag, user: AbstractUser) -> None:
    handle_user_tag_stats(tag, user)
    create_follow(tag, user)


def delete_follow_tag(tag: Tag, user: AbstractUser) -> None:
    handle_user_tag_stats(tag, user)
    delete_follow(tag, user)

forum/forum/views/helpers.py
import time
from typing import Optional

from constance import config
from django.contrib.auth.models import AbstractUser
from django.db.models import QuerySet
from django.shortcuts import render

from common import utils
from common.utils import TabEnum
from forum import jobs
from forum.jobs.others import log_search
from forum.models import Question
from forum.views import search
from spaces.models import Space
from userauth.models import ForumUser
from wiwik_lib.models import user_model_defer_fields
from wiwik_lib.utils import paginate_queryset


def get_questions_queryset(
    base_queryset: QuerySet,
    tab: Optional[str],
    query: Optional[str],
    user: Optional[AbstractUser],
) -> QuerySet:
    base_queryset = base_queryset.select_related(
        "author",
    ).defer(*user_model_defer_fields("author"), "source", "source_id", "link")
    start_time = time.time()
    if query is not None:
        qs = search.query_method(base_queryset, query)
    elif tab == TabEnum.MOST_VIEWED.value:
        qs = base_queryset.all().order_by("-views")
    elif tab == TabEnum.UNRESOLVED.value:
        qs = base_queryset.filter(type__in=Question.POST_TYPE_ACCEPTING_ANSWERS, has_accepted_answer=False).order_by(
            "-created_at"
        )
    elif tab == TabEnum.UNANSWERED.value:
        qs = base_queryset.filter(type__in=Question.POST_TYPE_ACCEPTING_ANSWERS, answers_count=0).order_by(
            "-created_at"
        )
    else:
        qs = base_queryset.all().order_by("-type", "-created_at")
    if query and user:
        mstaken = int((time.time() - start_time) * 1000)
        first_five = list(qs.values_list("id", flat=True)[:5])
        jobs.start_job(log_search, user, query, first_five, mstaken)
    return qs


def get_restricted_space_ids(user: ForumUser) -> list[int]:
    return list(Space.objects.filter(restricted=True).values_list("id", flat=True))


def render_questions(request, base_qs: QuerySet, header: str, extra: dict = None):
    tab = utils.get_request_tab(request)
    q = utils.get_request_param(request, "q", None)
    restricted_spaces = get_restricted_space_ids(request.user)
    all_questions_qs = get_questions_queryset(base_qs.exclude(space_id__in=restricted_spaces), tab, q, request.user)
    all_questions_qs = all_questions_qs.prefetch_related(
        "tags",
    )
    page_number = int(utils.get_request_param(request, "page", "1"))
    page_qs = paginate_queryset(all_questions_qs, page_number, config.QUESTIONS_PER_PAGE)
    context = {
        "all_questions": page_qs,
        "tab": tab if q is None else None,
        "header": header,
        "tag_watched": None,
    }
    if q:
        context["query"] = q
    if extra is not None:
        context = context | extra
    return render(request, "main/questions.html", context)

forum/forum/views/view_partial_user_navbar.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render


@login_required
def view_partial_user_navbar(request):
    return render(
        request,
        "partial.user.navbar.html",
    )

forum/forum/views/view_user_tags.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.urls import reverse, resolve

from forum.views.follow_models import delete_follow_tag, create_follow_tag
from tags.apps import logger
from tags.models import Tag


def _parse_redirect_url(request, tag_word: str) -> str:
    redirect_url = request.META.get("HTTP_REFERER", None) or reverse(
        "forum:tag",
        args=[
            tag_word,
        ],
    )
    try:
        resolve(redirect_url)
    except Exception:
        logger.warning(f"Bad redirect url: {redirect_url}")
        redirect_url = reverse(
            "forum:tag",
            args=[
                tag_word,
            ],
        )
    return redirect_url


@login_required
def view_user_follow_tag(request, tag_word: str):
    redirect_url = request.META.get("HTTP_REFERER", None) or reverse(
        "forum:tag",
        args=[
            tag_word,
        ],
    )
    tag = Tag.objects.filter(tag_word=tag_word).first()
    if tag is None:
        return redirect("forum:tag", tag_word=tag_word)
    create_follow_tag(tag, request.user)
    return redirect(redirect_url)


@login_required
def view_user_unfollow_tag(request, tag_word: str):
    redirect_url = _parse_redirect_url(request, tag_word)
    tag = Tag.objects.filter(tag_word=tag_word).first()
    if tag is None:
        return redirect("forum:tag", tag_word=tag_word)
    delete_follow_tag(tag, request.user)
    return redirect(redirect_url)

forum/forum/templates/main/includes/partial.questions-list.tag-popover.html
{% load wiwik_template_tags %}
{% if t.description %}
    <a class="btn btn-question-tag"
       data-bs-toggle="popover"
       data-bs-trigger="hover"
       data-bs-placement="bottom"
       data-content-id="popover-{{ q_id }}-{{ t.tag_word }}"
       href="{% url 'forum:tag' t.tag_word %}">
        {% if t.tag_word in tags_watched %}
            <span class="material-icons">visibility</span>
        {% endif %}
        {{ t.tag_word }}
    </a>
    <div style="display: none;" id="popover-{{ q_id }}-{{ t.tag_word }}">

        <div class="tag-popover popover" role="tooltip">
            <div class="popover-arrow"></div>

            <div class="popover-body p-1">
                <div class="card-subtitle text-muted">
                    <span class="orange-color">{{ t.number_followers | humanize_number }} watchers</span>
                    {{ t.number_of_questions | humanize_number }} questions
                </div>
                <div class="card-text text-dark pb-2">
                    {{ t.description }}
                    <a href="{% url 'forum:tag' t.tag_word %}">
                        View questions
                    </a>
                </div>
                {% if t.related_tags %}
                    <div class="card-subtitle text-muted">
                        Related tags
                        {% for r_tag in t.related_tags %}
                            <a class="btn btn-question-tag" href="{% url 'forum:tag' r_tag %}">
                                {{ r_tag }}
                            </a>
                        {% endfor %}
                    </div>
                {% endif %}
                {% if t.experts_list %}
                    <div class="card-subtitle text-muted">
                        Leaders:
                        {% for u in t.experts_list %}
                            <a href="{% url 'userauth:profile' u.username 'questions' %}"
                               style="margin-left: 5px;">
                                <img src="{{ u.profile_pic.url }}"
                                     onerror="this.onerror=null; this.src='/media/default_pics/no_pic.jpg'"
                                     alt="" height="16" width="16" style="display: block"/>
                                {{ u.display_name }}
                            </a>
                        {% endfor %}
                    </div>
                {% endif %}
                {% if t.stars_list %}
                    <div class="card-subtitle text-muted">
                        Rising stars:
                        {% for u in t.stars_list %}
                            <a href="{% url 'userauth:profile' u.username 'questions' %}"
                               style="margin-left: 5px;">
                                <img src="{{ u.profile_pic.url }}"
                                     onerror="this.onerror=null; this.src='/media/default_pics/no_pic.jpg'"
                                     alt="" height="16" width="16" style="display: block"/>
                                {{ u.display_name }}
                            </a>
                        {% endfor %}
                    </div>
                {% endif %}
                <div class="pull-right my-2">
                    <a href="{% url 'tags:info' t.tag_word %}"
                       class="btn btn-sm btn-outline-primary">
                        Tag info
                    </a>
                    {% if t.tag_word in tags_watched %}
                        <a href="{% url 'forum:unwatch_tag' t.tag_word %}"
                           class="btn btn-sm btn-outline-secondary">
                            <span class="material-icons">visibility_off</span> Unwatch tag
                        </a>
                    {% else %}
                        <a href="{% url 'forum:watch_tag' t.tag_word %}"
                           class=" btn btn-sm btn-outline-primary">
                            <span class="material-icons">visibility</span> Watch tag
                        </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% else %}
    <a class="btn btn-question-tag"
       href="{% url 'forum:tag' t.tag_word %}">
        {% if t.tag_word in tags_watched %}
            <span class="material-icons">visibility</span>
        {% endif %}
        {{ t.tag_word }}
    </a>
{% endif %}

forum/forum/templates/main/includes/partial.thread.question-tags.html
{% load static %}
<h3>Tags</h3>
{% for t in q.tags.all %}
    {% include 'main/includes/tag-popover.template.html' with q_id=q.id t=t %}
{% endfor %}

forum/forum/templates/main/includes/questions.watched-tags.template.html
{% if tags_watched %}
    <div id="watched-tags">
        <h3>Watched tags</h3>

        <div>
            {% for tag_word in tags_watched %}
                <a class="btn btn-question-tag m-1" href="{% url 'forum:tag' tag_word %}">
                    {{ tag_word }}
                </a>
            {% endfor %}
        </div>
        <hr class="my-2" style="color:#bbbbbb;"/>
    </div>
{% endif %}

forum/forum/templates/main/includes/thread.answer.template.html
{% load wiwik_template_tags %}
<div style="display: flex;flex-direction: row;" id="answer_{{ a.pk }}">
    <div style="display: flex; flex-direction:column;" class="pt-2">
        <div>
            <a href="{% url 'forum:upvote' q.pk 'answer' a.pk %}">
                <span class="material-icons vote-button-icon"
                      style="color:{% if a.user_upvoted %}coral{% else %}#555{% endif %};">thumb_up_off_alt</span>
            </a>
            <div class="text-center single-question-votes">
                {{ a.votes | humanize_number }}
            </div>
            <a href="{% url 'forum:downvote' q.pk 'answer' a.pk %}">
                <i style="color:{% if a.user_downvoted %}coral{% else %}#555{% endif %};"
                   class="material-icons vote-button-icon">thumb_down_off_alt</i>
            </a>
            {% if a.is_accepted %}
                <div class="pt-1 pb-1">
                    <i class="accept-answer-button-accepted material-icons">done</i>
                </div>
            {% else %}
                {% if show_accept_button %}
                    <div class="pt-1 pb-1">
                        <a href="{% url 'forum:answer_accept' q.pk a.pk %}">
                            <i class="accept-answer-button material-icons">done</i>
                        </a>
                    </div>
                {% endif %}
            {% endif %}
        </div>
    </div>
    <div style="width:100%;overflow-x: unset; padding-left: 10px;padding-right: 10px;">
        <div class="user-content">
            {{ a.content | markdownify }}
        </div>
        <div>
            {% include 'main/includes/thread.user_card.template.html' with item=a %}
            <a class="btn btn-sm text-secondary"
               data-bs-container="body"
               data-bs-placement="bottom"
               data-bs-toggle="popover"
               title="Share a link to this question"
               data-bs-content="{{ a.share_link }}">
                Share
            </a>

            {% if user == a.author or show_edit_button %}
                <a class="btn btn-sm text-secondary" href="{% url 'forum:answer_edit' a.pk %}">
                    Edit
                </a>
            {% endif %}
            {% if show_delete_a_button or user == a.author %}
                <a class="btn btn-sm text-secondary"
                   href="{% url 'forum:answer_delete' q.pk a.pk %}">
                    Delete
                </a>
            {% endif %}
            <a class="btn btn-sm text-secondary"
               data-bs-toggle="modal"
               data-bs-target="#flag-model-modal-answer-{{ a.pk }}">
                Flag
            </a>
        </div>

        <div hx-get="{% url 'forum:post_comments' 'answer' a.id %}"
             hx-trigger="load" hx-swap="outerHTML">
        </div>
        {% include 'main/includes/flag-model-modal.template.html' with q_pk=q.pk model_pk=a.pk model_name='answer' model_name_for_user='answer' %}
    </div>
</div>


<hr/>

forum/forum/templates/main/includes/thread.question-header.template.html
{% load wiwik_template_tags %}
<!-- question title -->
<div class="row mt-3" id="question_{{ q.pk }}">
    {% if q.is_article %}
        <div class="text-small">
            <span class="material-icons">article</span>
            Knowledge article
        </div>
    {% endif %}
    <div class="col-9">
        <h2>{{ q.title | markdownify }}</h2>
    </div>
    <div class="col-3 p-2">
        <button onclick="location.href='{% url 'articles:create' %}'"
                class="btn btn-primary btn-sm m-1"
                type="submit">
            Propose article
        </button>
        <button onclick="location.href='{% url 'forum:ask' %}'"
                class="btn btn-primary btn-sm m-1"
                type="submit">
            Ask Question
        </button>
    </div>
</div>
<hr/>

forum/forum/templates/main/includes/thread.question.template.html
{% load wiwik_template_tags %}
<!-- Question body -->
<div style="display: flex;flex-direction: row;">
    <div style="display: flex; flex-direction:column;" class="pt-2">
        <div>
            <a href="{% url 'forum:upvote' q.pk 'question' q.pk %}">
                <i style="color:{% if q.user_upvoted %}coral{% else %}#555{% endif %};"
                   class="material-icons vote-button-icon">thumb_up_off_alt</i>
            </a>
            <div class="text-center single-question-votes">{{ q.votes | humanize_number }}</div>
            <a href="{% url 'forum:downvote' q.pk 'question' q.pk %}">
                <i style="color:{% if q.user_downvoted %}coral{% else %}#555{% endif %};"
                   class="material-icons vote-button-icon">thumb_down_off_alt</i>
            </a>
        </div>
        <div class="mt-2 pt-1 pb-1">
            {% if bookmarked %}
                <a href="{% url 'forum:unbookmark' q.pk %}">
                    <span style="color:coral;" class="bookmark-button material-icons">bookmark</span>
                </a>
            {% else %}
                <a href="{% url 'forum:bookmark' q.pk %}">
                     <span style="color:#babfc3;"
                           class="bookmark-button material-icons">bookmark_border</span>
                </a>
            {% endif %}
            {% if num_bookmarks > 0 %}
                <div class="text-center">
                    {{ num_bookmarks }}
                </div>
            {% endif %}
        </div>
    </div>
    <!-- right (post-container) -->
    <div class="post-container">
        {% if not q.is_accepting_answers %}
            {% include 'main/includes/thread.question-status.template.html' %}
        {% endif %}
        <div class="user-content">
            {{ q.content | markdownify }}
        </div>
        {% include 'main/includes/thread.user_card.template.html' with item=q %}

        {% if display_comments_and_buttons %}
            <!-- Questions buttons: Share link, follow/unfollow, Edit, Delete -->
            <div style="display: flex;justify-content: flex-start;">
                <a class="btn btn-sm text-secondary"
                   data-bs-container="body"
                   data-bs-placement="bottom"
                   data-bs-toggle="popover"
                   title="Share a link to this question"
                   data-bs-content="{{ q.share_link }}">
                    Share
                </a>
                {% if show_follow %}
                    <a class="btn btn-sm text-secondary" href="{% url 'forum:follow' q.pk %}">
                        Follow
                    </a>
                {% else %}
                    <a class="btn btn-sm text-secondary" href="{% url 'forum:unfollow' q.pk %}">
                        Unfollow
                    </a>
                {% endif %}
                {% if show_edit_button %}
                    <a class="btn btn-sm text-secondary" href="{% url 'forum:question_edit' q.pk %}">
                        Edit
                    </a>
                {% endif %}
                {% if show_delete_q_button %}
                    <a class="btn btn-sm text-secondary"
                       href="{% url 'forum:question_delete' q.pk %}">
                        Delete
                    </a>
                {% endif %}
                <a class="btn btn-sm text-secondary"
                   href="{% url 'forum:markdown' q.pk %}">
                    Markdown
                </a>
                <a class="btn btn-sm text-secondary"
                   data-bs-toggle="modal"
                   data-bs-target="#flag-model-modal-question-{{ q.pk }}"
                   style="cursor: pointer">
                    {% if user.is_moderator and q.flags.count > 0 %}
                        <span class="badge bg-danger">{{ q.flags.count }}</span>
                    {% endif %}
                    Flag
                </a>
            </div>
            <div hx-get="{% url 'forum:post_comments' 'question' q.id %}"
                 hx-trigger="load" hx-swap="outerHTML">
            </div>
            {% include 'main/includes/thread.invite-to-question.template.html' with q_pk=q.pk %}
            {% include 'main/includes/flag-model-modal.template.html' with q_pk=q.pk model_pk=q.pk model_name='question' model_name_for_user='question' %}
        {% endif %}
    </div>
</div>
<hr/>