forum/badges/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("<int:badge_id>/", views.view_single_badge, name="detail"),
    path("list/", views.view_badges, name="list"),
]

forum/forum/urls.py
from django.urls import path

from . import views
from .views.feed import LatestEntriesFeed

urlpatterns = [
    path("", views.view_home, name="home"),
    path("questions/", views.view_questions, name="list"),
    path("questions/tag/<str:tag_word>/", views.view_tag_questions_list, name="tag"),
    path("questions/<int:pk>/", views.view_single_question, name="thread"),
    path("questions/ask", views.view_askquestion, name="ask"),
    path("question/<int:pk>/edit", views.view_editquestion, name="question_edit"),
    path(
        "questions/answer/<int:answer_pk>/edit",
        views.view_editanswer,
        name="answer_edit",
    ),
    path("question/<int:pk>/delete", views.view_delete_question, name="question_delete"),
    path(
        "question/<int:question_pk>/delete/<int:answer_pk>",
        views.view_delete_answer,
        name="answer_delete",
    ),
]
# Partials
urlpatterns += [
    path(
        "questions/<int:question_pk>/tags",
        views.view_partial_question_tags,
        name="question_tags",
    ),
    path(
        "<str:post_type>/<int:post_pk>/comments",
        views.view_partial_post_comments,
        name="post_comments",
    ),
    path(
        "questions/<int:question_pk>/invites",
        views.view_partial_invites,
        name="questions_invites",
    ),
    path("users/navbar", views.view_partial_user_navbar, name="user_navbar"),
    path("similar-questions/", views.view_similar_questions, name="similar"),
    path("tags/<int:pk>/popover", views.view_partial_tag_popover, name="tag_popover"),
]
# Actions
urlpatterns += [
    path("question/<int:pk>/follow/", views.view_follow_question, name="follow"),
    path("question/<int:pk>/unfollow/", views.view_unfollow_question, name="unfollow"),
    path(
        "question/<int:question_pk>/bookmark",
        views.view_bookmark_question,
        name="bookmark",
    ),
    path(
        "question/<int:question_pk>/unbookmark",
        views.view_unbookmark_question,
        name="unbookmark",
    ),
    path("usertags/<str:tag_word>/watch", views.view_user_follow_tag, name="watch_tag"),
    path(
        "usertags/<str:tag_word>/unwatch",
        views.view_user_unfollow_tag,
        name="unwatch_tag",
    ),
    path(
        "question/<int:question_pk>/invite_to_question",
        views.view_invite_to_question,
        name="invite",
    ),
    path(
        "question/<int:question_pk>/download_markdown",
        views.view_download_thread,
        name="markdown",
    ),
    path(
        "question/<int:pk>/upvote_comment/<str:parent_model_name>/<int:comment_pk>",
        views.view_upvote_comment,
        name="comment_upvote",
    ),
    path(
        "question/<int:pk>/delete_comment/<str:model>/<int:comment_id>",
        views.view_deletecomment,
        name="comment_delete",
    ),
]
# Automatic actions
urlpatterns += [
    path(
        "question/<int:pk>/upvote/<str:model_name>/<int:model_pk>",
        views.view_upvote,
        name="upvote",
    ),
    path(
        "question/<int:pk>/downvote/<str:model_name>/<int:model_pk>",
        views.view_downvote,
        name="downvote",
    ),
    path(
        "mark_as_seen/<int:vote_activity_pk>/",
        views.view_mark_as_seen,
        name="mark_seen",
    ),
    path("mark_all_as_seen/", views.view_all_mark_as_seen, name="mark_all_seen"),
    path(
        "question/<int:question_pk>/accept/<int:answer_pk>",
        views.view_acceptanswer,
        name="answer_accept",
    ),
]

urlpatterns += [
    path("users-autocomplete/", views.view_users_autocomplete, name="users_autocomplete"),
    path("users-get/", views.view_get_users_data, name="users-get"),
    path("image-upload/", views.view_image_upload, name="image_upload"),
]
# Slack
urlpatterns += [
    path("integrations/slack_post/", views.view_slack_post, name="slack-post"),
    path(
        "integrations/tags_autocomplete/",
        views.view_tags_autocomplete_for_slack,
        name="slack-tags-autocomplete",
    ),
    path("integrations/slack_search/", views.search_from_slack, name="slack-search"),
]

# RSS
urlpatterns += [
    path("rss/feed/", LatestEntriesFeed()),
    path("editing-help/", views.view_markdown_help),
]

# One time code
from wiwik_lib.templatetags.wiwik_template_tags import check_latex_config  # noqa: E402
from forum.integrations.slack_api import configure_slack_client  # noqa: E402

check_latex_config()
configure_slack_client()

forum/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include(("forum.urls", "forum"), namespace="forum")),
    path("articles/", include(("articles.urls", "articles"), namespace="articles")),
    path("BB-aDmin/", admin.site.urls),  # intentionally non-standard to prevent casual hacking tries.
    path("scheduler/", include("scheduler.urls")),
    path("accounts/", include("allauth.urls")),
    path("users/", include(("userauth.urls", "userauth"), namespace="userauth")),
    path("badges/", include(("badges.urls", "badges"), namespace="badges")),
    path("tags/", include(("tags.urls", "tags"), namespace="tags")),
    path("general/", include(("wiwik_lib.urls", "wiwik_lib"), namespace="general")),
    path("spaces/", include(("spaces.urls", "spaces"), namespace="spaces")),
    path(
        "similarity/",
        include(("similarity.urls", "similarity"), namespace="similarity"),
    ),
]

if settings.DEBUG_TOOLS:
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

forum/tags/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.view_home, name="list"),
    path("query/", views.view_query, name="list_query"),
    path("<str:tag_word>/edit", views.view_edit_tag, name="edit"),
    path("<str:tag_word>/info", views.view_tag_info, name="info"),
    path(
        "tags-autocomplete/",
        views.view_tags_autocomplete,
        name="autocomplete",
    ),
    path("synonyms/", views.view_synonym_list, name="synonyms_list"),
    path(
        "synonyms/approve/<int:synonym_pk>",
        views.view_approve_synonym,
        name="synonyms_approve",
    ),
]

forum/userauth/urls.py
from django.urls import path, re_path

from . import views
from .admin import SendUserEmails

urlpatterns = [
    path("signup/", views.view_signup, name="signup"),
    path("login/", views.view_login, name="login"),
    path("logout/", views.view_logout, name="logout"),
    path(
        "staff-deactivate/<str:username>/",
        views.view_deactivate_user,
        name="deactivate_user",
    ),
    path("staff-activate/<str:username>/", views.view_activate_user, name="activate_user"),
    path("editprofile/", views.view_editprofile, name="edit"),
    path("editprofile/profile-pic/", views.view_profile_pic, name="profile_pic"),
    path("profile/<str:username>/<str:tab>/", views.view_profile, name="profile"),
    re_path(
        r"^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]+)/$",
        views.view_activate,
        name="activate",
    ),
    path("", views.view_users, name="list"),
    path("query/", views.view_users_query, name="list_query"),
    re_path(
        r"^unsubscribe/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]+)/$",
        views.view_unsubscribe,
        name="unsubscribe",
    ),
    path("email-users/", SendUserEmails.as_view(), name="admin_email"),
]

forum/userauth/views/common.py
def get_request_param(request, param_name, default_value):
    if request.GET and (param_name in request.GET):
        return request.GET[param_name]
    return default_value

forum/userauth/views/social_login_signal.py
import os

import urllib3
from allauth.account.signals import user_signed_up, user_logged_in
from constance import config
from django.core.files.base import ContentFile
from django.dispatch import receiver

from userauth.apps import logger
from userauth.models import ForumUser

http = urllib3.PoolManager()


def _populate_user_data_from_social(user: ForumUser, picture_only: bool = False) -> None:
    user_social_account = user.socialaccount_set.filter(provider="google").first()
    if user_social_account is None:
        logger.info(f"Could not find social account for user {user.username}")
        return
    user_data = user_social_account.extra_data
    picture_url = user_data.get("picture", None)
    if picture_url is not None:
        req = http.request("GET", picture_url)
        data = ContentFile(req.data)
        file_name = f"profile_pic_{user.username}.google.jpeg"
        user.profile_pic.save(file_name, data, save=True)
    if not picture_only and "email" in user_data:
        user.email = user_data["email"]
    if not picture_only and "name" in user_data:
        user.name = user_data["name"]
    user.save()


@receiver(user_signed_up)
def populate_profile(sociallogin, user: ForumUser, **kwargs):
    from forum.views.notifications import notify_slack_channel

    if sociallogin.account.provider != "google":
        return
    _populate_user_data_from_social(user)
    msg = f"User {user.display_name()} signed up to wiwik"
    notify_slack_channel(msg, config.SLACK_ADMIN_NOTIFICATIONS_CHANNEL)


@receiver(user_logged_in)
def fill_missing_data_in_profile(sociallogin, user: ForumUser, **kwargs):
    if sociallogin.account.provider != "google":
        return
    if os.path.isfile(user.profile_pic.path):
        return
    _populate_user_data_from_social(user, picture_only=True)

forum/userauth/views/tokens.py
from django.contrib.auth.tokens import PasswordResetTokenGenerator


class TokenGenerator(PasswordResetTokenGenerator):
    pass


account_activation_token = TokenGenerator()

forum/userauth/views/view_activate.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth import login
from django.shortcuts import redirect
from django.utils.encoding import force_str
from django.utils.http import urlsafe_base64_decode

from userauth.views.tokens import account_activation_token

User = get_user_model()


def view_activate(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist) as e:  # noqa: F841
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        messages.success(
            request,
            "Account activated successfully. Thank you for your email confirmation. Now you can login your account.",
        )
        return redirect("userauth:login")
    else:
        messages.error(request, "Activation link is invalid!", "danger")
        return redirect("userauth:login")

forum/userauth/views/view_editprofile.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import SuspiciousOperation
from django.shortcuts import render, redirect

from badges.jobs import review_bagdes_event
from badges.logic.utils import TRIGGER_EVENT_TYPES
from forum import jobs
from userauth.apps import logger


@login_required
def view_editprofile(request):
    def set_val(key: str, attribute: str, min_length: int = 1, max_length: int = 20_000):
        val = data.get(key, None)
        if not val:
            return
        if min_length and max_length and min_length <= len(val) <= max_length:
            setattr(user, attribute, val)
        else:
            msg = f"Expected value length between {min_length}..{max_length} for {key} but got {len(val)}"
            logger.warn(msg)
            raise SuspiciousOperation(msg)

    user = request.user
    if request.method == "POST":
        data = request.POST.dict()
        try:
            set_val("fullname", "name", 1, 100)
            set_val("about", "about_me")
            set_val("title", "title", 1, 100)
            set_val("github_handle", "github_handle", 1, 39)
            set_val("keybase_user", "keybase_user", 1, 16)
            user.email_notifications = data.get("email_notifications") == "on"
            user.save()
            messages.success(request, "Profile updated successfully")
            jobs.start_job(review_bagdes_event, TRIGGER_EVENT_TYPES["Edit profile"])
            return redirect("userauth:profile", username=user.username, tab="questions")
        except SuspiciousOperation as e:
            messages.error(request, e.args[0])

    return render(
        request,
        "userauth/editprofile.html",
        {
            "user": user,
            "title": "wiwik - Edit profile",
        },
    )

forum/userauth/views/view_login.py
from allauth.socialaccount.models import SocialApp
from django.contrib import messages
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import AnonymousUser
from django.shortcuts import render, redirect
from django.urls import reverse, resolve, Resolver404

from userauth.apps import logger


def view_login(request):
    if request.method == "POST":
        next_url = request.GET["next"] if "next" in request.GET else reverse("forum:home")
        try:
            resolve(next_url)
        except Resolver404:
            logger.warning(f"Bad redirect url: {next_url}")
            next_url = reverse("forum:home")
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are logged in as <b>{user.display_name()}</b>")
                url = next_url
                try:
                    resolve(next_url)
                except Resolver404:
                    url = reverse("forum:home")
                return redirect(url)
            else:
                messages.error(request, "Invalid username or password", "danger")
        else:
            messages.error(request, "Invalid username or password", "danger")
    if isinstance(request.user, AnonymousUser):
        form = AuthenticationForm()
        google_login_allowed = SocialApp.objects.filter(provider="google").count() > 0
        facebook_login_allowed = SocialApp.objects.filter(provider="facebook").count() > 0
        okta_login_allowed = SocialApp.objects.filter(provider="okta").count() > 0
        return render(
            request,
            "userauth/login.html",
            {
                "form": form,
                "google_login_allowed": google_login_allowed,
                "facebook_login_allowed": facebook_login_allowed,
                "okta_login_allowed": okta_login_allowed,
            },
        )
    else:
        messages.info(request, "User already logged in")
        return redirect("forum:list")

forum/userauth/views/view_logout.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect


@login_required
def view_logout(request):
    logout(request)
    messages.info(request, "Logged out successfully!")
    return redirect(settings.LOGIN_URL)

forum/userauth/views/view_profile_pic.py
import base64

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.files.base import ContentFile
from django.shortcuts import render, redirect


@login_required
def view_profile_pic(request):
    user = request.user
    if request.method == "POST":
        image_data = request.POST.dict()["cropped-profile-pic"]
        image_format, image_string = image_data.split(";base64,")
        extension = image_format.split("/")[-1]
        data = ContentFile(base64.b64decode(image_string))
        file_name = f"profile_pic_{user.username}.{extension}"
        user.profile_pic.save(file_name, data, save=True)

        messages.success(request, "Profile updated successfully")
        return redirect("userauth:profile", username=user.username, tab="questions")
    return render(request, "userauth/editprofile.html", {"user": user})

forum/userauth/views/view_staff_user_mgmt.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.shortcuts import redirect, get_object_or_404

from userauth.models import ForumUser


@login_required
def view_deactivate_user(request, username: str):
    if not request.user.is_staff or request.method != "GET" or request.user.username == username:
        raise PermissionDenied()
    u = get_object_or_404(ForumUser, username=username)
    u.is_active = False
    u.save()
    return redirect("userauth:profile", username=u.username, tab="questions")


@login_required
def view_activate_user(request, username: str):
    if not request.user.is_staff or request.method != "GET" or request.user.username == username:
        raise PermissionDenied()
    u = get_object_or_404(ForumUser, username=username)
    u.is_active = True
    u.save()
    return redirect("userauth:profile", username=u.username, tab="questions")

forum/userauth/templates/userauth/includes/editprofile.profile-pic-modal.template.html
<div class="modal fade" id="profile-pic-modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Profile picture</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>


            <form id="profile-pic-form" method="POST" enctype="multipart/form-data"
                  action="{% url 'userauth:profile_pic' %}">
                {% csrf_token %}
                <div class="modal-body">
                    <img id="profile-pic-croppie" src="{{ user.profile_pic.url }}" alt=""/>
                </div>
                <div class="modal-footer">
                    <div class="my-2">
                        <i class="material-icons">photo_camera</i>
                        <input type="file" id="fileInput" name="fileInput"/>
                        <input type="hidden" id="cropped-profile-pic" name="cropped-profile-pic"/>
                    </div>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button id="submit-button" type="button" class="btn btn-primary">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
    const profilePicElement = document.getElementById("profile-pic-croppie")
    const crop = new Croppie(profilePicElement, {
        enableExif: true,
        viewport: {
            width: 200,
            height: 200,
            type: 'square'
        },
        boundary: {
            width: 300,
            height: 300
        },
    });
    $('.cr-slider').attr({'min': 0.4, 'max': 1.5});

    document.getElementById("fileInput").addEventListener("change", (event) => previewImage(event));
    const previewImage = (event) => {
        const reader = new FileReader();
        reader.onload = () => {
            crop.bind({url: reader.result});
        }
        reader.readAsDataURL(event.target.files[0]);
    }
    document.getElementById('submit-button').addEventListener("click", () => {
            crop.result({type: 'base64', size: {width: 500, height: 500}}).then(function (croppedImage) {
                document.getElementById("cropped-profile-pic").value = croppedImage;
                document.getElementById("profile-pic-form").submit();
            });
        }
    )
</script>

forum/userauth/templates/userauth/includes/profile.answers.template.html
{% load userauth_tags %}
<div>
    <h4>Answers</h4>
    <hr>

    {% regroup user_answers by created_at.year as votes %}
    {% for year in votes %}
        <div>
            <h5>{{ year.grouper }}</h5>
            {% for item in year.list|sort_list_created_at %}
                <div class="row p-1">
                    <div class="col-md-1">
                        {{ item.created_at | date:"M d" }}
                    </div>
                    <div class="col-md-8">
                        <a href="{% url 'forum:thread' item.question_id %}">
                            {% if item.votes > 0 %}
                                <span class="reputation-badge badge bg-success"> {{ item.votes }} </span>
                            {% elif item.votes < 0 %}
                                <span class="reputation-badge badge bg-danger"> {{ item.votes }} </span>
                            {% else %}
                                <span class="reputation-badge badge bg-secondary"> {{ item.votes }} </span>
                            {% endif %}
                            {{ item.question.title }}
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% empty %}
        No answers
    {% endfor %}
</div>

forum/userauth/templates/userauth/includes/profile.badges.template.html
{% load userauth_tags %}
<div>
    <h4>Bagdes</h4>
    <hr/>
    <div>
        <div class="row p-1">
            {% for item in items %}
                <div class="col col-md-3 mb-2">
                    <a class="badge-btn"
                       href="{% url 'badges:detail' item.pk %}"
                       title="{{ item.description }}">
                        <i class="material-icons text-{{ item.badge_type }} icon-small">verified</i>
                        {{ item.name }}
                    </a>
                    {% if item.count > 1 %}
                        <small class="text-muted">
                            x {{ item.count }}
                        </small>
                    {% endif %}
                </div>
            {% empty %}
                <div class="col">
                    No badges, check out the <a href="{% url 'badges:list' %}">list</a>
                    of available badges and how to get them
                </div>
            {% endfor %}
        </div>
    </div>
</div>

forum/userauth/templates/userauth/includes/profile.cards.template.html
{% load wiwik_template_tags %}
{% load humanize %}
<div class="container mt-3 mb-3">
    <div class="row">
        <div class="col-md-4">
            <div class="card profile-card">
                <div class="profile-card-title">REPUTATION</div>
                <div class="card-body">
                    <h2>{{ seeuser.reputation_score |intcomma }}</h2>

                    {% for follow in user_top_tags %}
                        <div class="mb-1">
                            <a class="btn btn-question-tag"
                               href="{% url 'forum:tag' follow.tag.tag_word %}">
                                {{ follow.tag.tag_word }}
                            </a>
                            <span class="text-muted text-small">
                                    {{ follow.reputation }} pts,
                                    {{ follow.questions_by_user }} questions,
                                    {{ follow.answers_by_user }} answers
                            </span>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card profile-card">
                <div class="profile-card-title">BADGES</div>
                <div class="card-body">
                    <div class="row justify-content-center">
                        <div class="col col-3 mx-1 badge-gold">
                            <span class="material-icons text-gold">verified</span>
                            {{ seeuser.gold_badges | intcomma }}
                        </div>
                        <div class="col col-3 mx-2 badge-silver">
                            <span class="material-icons text-silver">verified</span>
                            {{ seeuser.silver_badges | intcomma }}
                        </div>
                        <div class="col col-3 mx-1 badge-bronze">
                            <span class="material-icons text-bronze">verified</span>
                            {{ seeuser.bronze_badges | intcomma }}
                        </div>
                    </div>
                    {% if last_badge %}
                        <div class="mt-3">
                            <small>Newest</small>
                            <br/>
                            <a class="badge-btn"
                               href="{% url 'badges:detail' last_badge.badge.pk %}"
                               title="{{ last_badge.badge.description }}">
                                <i class="material-icons text-{{ last_badge.badge.type }} icon-small">verified</i>
                                {{ last_badge.badge.name }}
                            </a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card profile-card">
                <div class="profile-card-title">IMPACT</div>
                <div class="p-2">
                    <h4 class="m-0">{{ seeuser.people_reached | humanize_number }} </h4>
                    <small>people reached</small>
                </div>
                <div class="row p-2">
                    <div class="col-6">
                        <h4 class="m-0">{{ seeuser.posts_edited | humanize_number }} </h4>
                        <small>posts edited</small>
                    </div>
                    <div class="col-6">
                        <h4 class="m-0">{{ seeuser.votes | humanize_number }} </h4>
                        <small>votes casted</small>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

forum/userauth/templates/userauth/includes/profile.tab-button.template.html
{% load userauth_tags %}
<li class="nav-item">
    <a class="profile-tab-link nav-link {% if selected == tab %}active{% endif %}"
       id="{{ tab }}-tab"
       href="{% url 'userauth:profile' seeuser.username tab %}"
       aria-controls="{{ tab }}"
       aria-selected="{% if selected == tab %}true{% else %}false{% endif %}">
        {{ title }} <small>({{ counters|get_val:tab }})</small>
    </a>
</li>

forum/userauth/templates/userauth/includes/tag-popover-userdata.template.html
{% load wiwik_template_tags %}
{% if tagstats.tag.description %}
    <a class="btn btn-question-tag m-2"
       data-bs-toggle="popover"
       data-bs-trigger="hover focus"
       data-bs-placement="bottom"
       data-content-id="popover-{{ tagstats.tag.tag_word }}"
       href="{% url 'forum:tag' tagstats.tag.tag_word %}">
        {{ tagstats.tag.tag_word }}
        {% if tagstats.reputation > 0 %}
            <small class="text-muted">x{{ tagstats.reputation }}</small>
        {% endif %}
    </a>
    <div style="display: none;" id="popover-{{ tagstats.tag.tag_word }}">
        <div class="tag-popover popover" role="tooltip">
            <div class="popover-arrow"></div>

            <div class="popover-body p-2">
                <div class="card-subtitle text-muted">
                    <span class="orange-color">{{ tagstats.tag.number_followers | humanize_number }} watchers</span>
                    {{ tagstats.tag.number_of_questions | humanize_number }} questions
                </div>
                <div class="card-text pb-2 text-dark">
                    {{ tagstats.tag.description }}
                    <a href="{% url 'forum:tag' tagstats.tag.tag_word %}"
                       class="text-primary">
                        View tag
                    </a>
                </div>
                {% if tagstats.tag.experts_list %}
                    <div class="card-subtitle text-muted">
                        Leaders:
                        {% for u in tagstats.tag.experts_list %}
                            <a href="{% url 'userauth:profile' u.username 'questions' %}"
                               style="margin-left: 5px;">
                                <img src="{{ u.profile_pic.url }}"
                                     alt="" height="16" width="16" style="display: block"/>
                                {{ u.display_name }}
                            </a>
                        {% endfor %}
                    </div>
                {% endif %}
                {% if tagstats.tag.stars_list %}
                    <div class="card-subtitle text-muted">
                        Rising stars:
                        {% for u in tagstats.tag.stars_list %}
                            <a href="{% url 'userauth:profile' u.username 'questions' %}"
                               style="margin-left: 5px;">
                                <img src="{{ u.profile_pic.url }}"
                                     alt="" height="16" width="16" style="display: block"/>
                                {{ u.display_name }}
                            </a>
                        {% endfor %}
                    </div>
                {% endif %}
                <div class="pull-right mb-2 mt-2">
                    <a href="{% url 'tags:info' tagstats.tag.tag_word %}"
                       class="btn btn-sm btn-outline-primary">
                        Tag info
                    </a>
                    {#TODO#}
                    {#                    {% if t.tag_word in tags_watched %}#}
                    {#                        <a href="{% url 'forum:unwatch_tag' t.tag_word %}"#}
                    {#                           class="btn btn-sm btn-outline-secondary">#}
                    {#                            <span class="material-icons">visibility_off</span> Unwatch tag#}
                    {#                        </a>#}
                    {#                    {% else %}#}
                    {#                        <a href="{% url 'forum:watch_tag' t.tag_word %}"#}
                    {#                           class=" btn btn-sm btn-outline-primary">#}
                    {#                            <span class="material-icons">visibility</span> Watch tag#}
                    {#                        </a>#}
                    {#                    {% endif %}#}
                </div>
            </div>
        </div>

    </div>
{% else %}
    <a class="btn btn-question-tag m-2"
       href="{% url 'forum:tag' tagstats.tag.tag_word %}">
        {{ tagstats.tag.tag_word }}
        {% if tagstats.reputation > 0 %}
            <small class="text-muted">x{{ tagstats.reputation }}</small>
        {% endif %}
    </a>
{% endif %}